services:
  - type: web
    name: timereach
    env: python
    buildCommand: |
      python -m venv .venv
      source .venv/bin/activate
      pip install --upgrade pip
      apt-get update && apt-get install -y gdal-bin libgdal-dev
      pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
    region: frankfurt
